### ISSUE TITLE
Bug with the Friends Window

### ISSUE THREAD

**Issue by ghost** [waylaidwanderer/Mist#1]
The "+ Add a Friend" thing doesn't properly move around when the window is resized vertically. It maintains its original orientation relative to the window when the window first opens up.  It still functions properly.

![Mist_error](https://f.cloud.github.com/assets/3589553/269182/f7de09fe-8f80-11e2-91ed-fc92eba8cc06.png)

**Comment by waylaidwanderer** [comment]
Not sure why I never noticed this before...

Anyway, I've just pushed a commit that fixes it. If you know how to compile the code from source, you can use the latest build, but if not, you'll have to wait a while for a fix since I'd like to wait for more bug reports and fix them first before making a new release.

**Comment by waylaidwanderer** [comment]
I'm going to mark this fixed and close it now.
